# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: isort
        name: Isort
        language: system
        entry: isort
        types: [python]
        args: ['--filter-files']
    -   id: black
        name: Black
        language: system
        entry: black
        types: [python]
    -   id: flake8
        name: Flake8
        language: system
        entry: flake8
        types: [python]
    -   id: mypy
        name: MyPy
        language: system
        entry: mypy
        types: [python]
