# Config file for automatic testing at travis-ci.org
language: python
os: linux
dist: xenial
python:
  - 3.8
  - 3.7
  - 3.6

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - black --check .
  - flake8
  - pytest
