language: python
os: linux
dist: xenial
python:
  - 3.8
  - 3.7
  - 3.6

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - black --check .
  - flake8
  - coverage run --source esparto -m pytest

addons:
  sonarcloud:
    organization: "domvwt"
    
after_success:
  - sonar-scanner
  - bash <(curl -s https://codecov.io/bash)
