# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.7
  - 3.6

before install:
  - pip install poetry

install:
  - poetry install

script:
  - black --check .
  - flake8 --max-line-length 120 --ignore=E203
  - pytest
